### ISSUE TITLE
AssertionError while querying TXT record

### ISSUE THREAD

**Issue by kirankumbhar** [gera2ld/async-doh#2]
Hello, First of all, amazing work on the doh library!
I was trying to get the TXT record for `example.com` which errored out the ParseError. 

Code:

```
import asyncio
from async_doh.client import DoHClient


async def async_query(domain):
    async with DoHClient() as client:
        return await client.query("https://1.1.1.1/dns-query", domain, "TXT")

result = asyncio.run(async_query("example.com"))
print(result)
```
Error Traceback:
```
Traceback (most recent call last):
  File "gen.py", line 10, in <module>
    result = asyncio.run(async_query("example.com"))
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "gen.py", line 7, in async_query
    return await client.query("https://1.1.1.1/dns-query", domain, "TXT")
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/site-packages/async_doh/client.py", line 49, in query
    return await self.request_message(url, req, method)
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/site-packages/async_doh/client.py", line 41, in request_message
    result = DNSMessage.parse(data)
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/site-packages/async_dns/core/record.py", line 313, in parse
    l, ans.an = ans.parse_entry(RESPONSE, data, l, an)
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/site-packages/async_dns/core/record.py", line 294, in parse_entry
    l = r.parse(data, l)
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/site-packages/async_dns/core/record.py", line 196, in parse
    _, self.data = utils.load_message(data, l)
  File "/Users/scorpionk/.pyenv/versions/3.8.6/lib/python3.8/site-packages/async_dns/core/utils.py", line 39, in load_message
    assert cursor is not None, ParseError(data, offset)
AssertionError
```

If I do the curl of `example.com` TXT record using Cloudflare DNS then I get the following result.
Command:
`curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=TXT' | python -m json.tool`

Output:
```
 {
    "Status": 0,
    "TC": false,
    "RD": true,
    "RA": true,
    "AD": true,
    "CD": false,
    "Question": [
        {
            "name": "example.com",
            "type": 16
        }
    ],
    "Answer": [
        {
            "name": "example.com",
            "type": 16,
            "TTL": 86400,
            "data": "\"v=spf1 -all\""
        },
        {
            "name": "example.com",
            "type": 16,
            "TTL": 86400,
            "data": "\"8j5nfqld20zpcyr8xjw0ydcfq9rk8hgm\""
        }
    ]
}
```
It would be great if this can be fixed.
Thanks.

**Comment by gera2ld** [comment]
Hi, sorry for the issue.
Can you try the latest alpha version `0.3.0-alpha.0`? It should have been fixed there.

**Comment by kirankumbhar** [comment]
It worked after installing `0.3.0-alpha.0` 👍🏼  
Thank you for the quick response!

**Comment by gera2ld** [comment]
FYI v0.3.0 is released now.
